---
- name: To install httpd & apache service on rhel/debian OS
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: install httpd service
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    notify: start httpd
  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: true
    when: ansible_os_family == "Debian"
