---

- name: To Create and Run Script
  hosts: all
  gather_facts: false
  tasks:
  - name: create script file
    copy:
      src: /root/playbooks/script_run1.sh
      dest: /opt/script/
      owner: root
      group: root
      mode: ugo=rx


