---
- name: To stop http & apache2
  hosts: all
  become: true
  tasks: 
  - name: to stop httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: to stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
