---
- name: To Stop and Remove Web Service
  hosts: all
  gather_facts: true
  
  tasks:
  - name: to stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: to remove httpd pkg
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: to stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: to remove apache2 pkg
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
