---
- name: to unstall service
  hosts: all
  become: true  
  tasks: 
  - name: to  stopped httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: to uninstall httpd
    yum: 
      name: http
      state: absent
    when: ansible_os_family == "RedHat"

  - name: stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt: 
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
